spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devdb
    username: root
    password: pass
  batch:
    jdbc:
      initialize-schema: always

test:
  naverpay:
    transact:
      filename: "E:\\work\\java\\project\\jayMarket\\resource\\test.csv"